# docker image path in artifactory
artifactoryPath: "wqp_ui"
# name of the docker image
dockerImageName: "wqp_ui"
# type of build
gitRepoUrl: "https://github.com/NWQMC/WQP_UI.git"
# the Jenkins credential ID to be use when pushing commits
gitRepoCredentialsId: "Jenkins-GitHub-Read-Write-Token"
# name of the deploy job to trigger
deployJobName: "wqp-ui-deploy"
# name of the project
projectName: "wqp-external"
# location of the Dockerfile
buildContext: "./server/"
# maximum amount of RAM for running Docker containers in the service
memory: 512
# name of the application or service
applicationName: "wqp_ui"
# port that is exposed by your container
containerPort: 5050
# string parameter specifying a path that ALB should use to verify that your application is alive
healthCheck: "/wqp/robots.txt"
# configuration repository paths
configRepoPath: "wma/docker/wqp/wqp_ui"
configCredentialsId: "wma-eto-eb-rsa"
urlRules:
  - type: forward
    conditions:
      - "/*"
    priority: 504
tags:
  wma:costCenter: TBD
  wma:organization: IOW
  wma:contact: jkreft@usgs.gov
  wma:taggingVersion: 0.0.1
  wma:project_id: wqp
